# Generated by Django 4.2.7 on 2023-12-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
    ]
