# Generated by Django 4.2.7 on 2023-12-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_rename_text_recipereview_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
    ]
