# Generated by Django 4.2.7 on 2023-12-15 09:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_recipe_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images'),
        ),
    ]
