# Generated by Django 4.2.7 on 2023-12-15 10:37

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_recipe_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', cloudinary.models.CloudinaryField(max_length=255, verbose_name='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='images',
        ),
        migrations.AddField(
            model_name='recipe',
            name='images',
            field=models.ManyToManyField(blank=True, to='recipe.recipeimages'),
        ),
    ]
