# Generated by Django 4.2.7 on 2023-12-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_recipeimages_recipe_recipeimages_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeimages',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipeimages',
            name='user',
        ),
    ]
