# Generated by Django 4.2.7 on 2023-12-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_recipeimages_recipe_recipeimages_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='recipe_images', to='recipe.recipeimages'),
        ),
    ]
