# Generated by Django 4.2.7 on 2023-12-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_recipe_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='images',
        ),
        migrations.RemoveField(
            model_name='recipeimages',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipeimages',
            name='user',
        ),
    ]
