# Generated by Django 4.2.7 on 2023-12-17 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0014_remove_recipe_images_remove_recipeimages_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='recipe_images', to='recipe.recipeimages'),
        ),
        migrations.AddField(
            model_name='recipeimages',
            name='recipe',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeimages',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipeimages',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
