# Generated by Django 4.2.7 on 2023-12-18 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_recipe_images_recipeimages_recipe_recipeimages_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='images',
        ),
        migrations.DeleteModel(
            name='RecipeImages',
        ),
    ]
